# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: Server/

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Test'
  inputs:
    command: 'test'
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Dotnet Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration release --output $(Build.ArtifactStagingDirectory)'
    workingDirectory: 'Server/'

- task: PublishBuildArtifacts@1
  displayName: 'Dotnet Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DeleteFiles@1
  displayName: 'Delete JUnit files'
  inputs:
    SourceFolder: 'Client/junit'
    Contents: 'TESTS-*.xml'

- task: Npm@1
  displayName: 'Angular npm install'
  inputs:
    command: 'custom'
    workingDir: 'Client/'
    customCommand: 'install -f'

- task: Npm@1
  displayName: 'Angular Build'
  inputs:
    command: custom
    customCommand: run build -- --prod
    workingDir: 'Client/'

- task: Npm@1
  displayName: 'Angular Test'
  inputs:
    command: 'custom'
    workingDir: 'Client/'
    customCommand: 'run test -- --watch=false'

- task: PublishTestResults@2
  displayName: 'Angular Publish Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TESTS-*.xml'
    mergeTestResults: true
    testRunTitle: 'Angular'

- task: PublishPipelineArtifact@0
  displayName: 'Angular Publish Artifacts'
  inputs:
    artifactName: 'angular'
    targetPath: 'Client/dist'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/client-react'
    output_location: '/client-react/build'
    azure_static_web_apps_api_token: $(deployment_token)